# NB this is a modified version of:
#      https://github.com/linuxkit/linuxkit/blob/46d4edc967b5a9de705840d30c83b83fedabb492/examples/docker.yml
#      https://github.com/linuxkit/linuxkit/blob/46d4edc967b5a9de705840d30c83b83fedabb492/examples/sshd.yml
#      https://github.com/linuxkit/linuxkit/blob/46d4edc967b5a9de705840d30c83b83fedabb492/examples/logging.yml
kernel:
  image: quay.io/tinkerbell/hook-kernel:5.10.57
  # NB this is NOT USED when the kernel is booted from tinkerbell.
  # NB tty0 (or console) represent the current virtual terminal.
  cmdline: console=ttyS0 console=tty1
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:cc02c2af9c928c2faeccbe4edc78bd297ad91866
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a
  - linuxkit/memlogd:9b0e8a5b3f67672234170d88833163caf7898984
onboot:
  - name: sysctl
    image: linuxkit/sysctl:02d2bd74509fd063857ceb4c4f502f09ee4f2e0a
  - name: rngd1
    image: linuxkit/rngd:bdabfe138f05f7d48396d2f435af16f5a6ccaa45
    command: ["/sbin/rngd", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:3498aa99c90a29439b5a1926f6ffcd75c270372c
  - name: dhcpcd
    image: linuxkit/dhcpcd:1033f340e2d42f86a60aab70752346f0045ea388
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:bdabfe138f05f7d48396d2f435af16f5a6ccaa45
  - name: dhcpcd
    image: linuxkit/dhcpcd:1033f340e2d42f86a60aab70752346f0045ea388
  - name: ntpd
    image: linuxkit/openntpd:66f25a516c7460f5e49195309cf276903741c428
  - name: logwrite
    image: linuxkit/logwrite:e64e0f06e485e3542b58f3517da3bc13f246d208
  - name: kmsg
    image: linuxkit/kmsg:df84eda2a82d5e24ddfe241831af3efb13a1a557
  - name: promtail
    image: grafana/promtail:2.3.0
    binds.add:
      - /etc/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/host/var/log
      - /var/run/promtail:/var/run/promtail
    runtime:
      mkdir:
        - /var/run/promtail
  - name: getty
    image: linuxkit/getty:ed32c71531f5998aa510847bb07bd847492d4101
    env:
      - INSECURE=true
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
  - name: sshd
    image: linuxkit/sshd:add8c094a9a253870b0a596796628fd4ec220b70
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
  - name: docker
    image: quay.io/tinkerbell/hook-docker:0.0
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "nodev", "noexec", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
      - /var/run/docker:/var/run
      - /var/run/worker:/worker
      - /dev/console:/dev/console
      - /dev:/dev
    runtime:
      mkdir:
        - /var/run/docker
        - /var/run/worker
  - name: bootkit
    image: quay.io/tinkerbell/hook-bootkit:0.0
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "nodev", "noexec", "relatime"]
    binds:
      - /var/run/docker:/var/run
    runtime:
      mkdir:
        - /var/run/docker
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: etc/profile.d/local.sh
    contents: |
      alias logread='/proc/1/root/usr/bin/logread'
      alias l='ls -lF'
      alias ll='l -a'
      alias ctr='ctr -n services.linuxkit'
      alias docker='ctr tasks exec --tty --exec-id shell docker docker'
    mode: "0644"
  - path: etc/promtail/config.yml
    source: tmp/promtail-config.yml
    mode: "0644"
  # see https://github.com/linuxkit/linuxkit/blob/master/docs/faq.md#enabling-and-controlling-containerd-logs
  # NB this is only available in linuxkit after v0.8.
  - path: etc/containerd/runtime-config.toml
    contents: |
      cliopts="--log-level debug"
      stderr="/var/log/containerd.log.txt"
      stdout="/var/log/containerd.out.log.txt"
    mode: "0644"
  - path: etc/docker/daemon.json
    # TODO instead of returning the container host hostname, return the host hostname.
    # TODO get the loki base url from the metadata service.
    # TODO create this file at docker bootstrap instead; in a way that integrates values from the metadata service.
    # NB loki-relabel-config is executed once per container.
    # NB loki-pipeline-stages is executed once per container log line.
    # NB the filename label is set once per container.
    # NB the source label is set per container log line.
    contents: |
      {
        "debug": true,
        "log-driver": "loki",
        "log-opts": {
          "labels": "worker_id,workflow_id",
          "loki-url": "@@loki_push_url@@",
          "loki-external-labels": "job=container,container_name={{.Name}}",
          "loki-relabel-config": "# drop filename, we have no use for it.\n- regex: filename\n  action: labeldrop\n# always use the host hostname as the host that generated the container logs.\n- target_label: host\n  replacement: linuxkit\n",
          "loki-pipeline-stages": "# rename container_name to source.\n- labels:\n    source: container_name\n- labeldrop:\n    - container_name\n",
          "max-size": "10m",
          "max-file": "3"
        }
      }
